dist: xenial

language: scala

scala:
   - 2.13.2
   - 2.12.11

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier

install:
  - pip install --user codecov
  - rvm use 2.6.0 --install --fuzzy
#  - pip install --user graphviz
  - sudo apt-get install graphviz
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.8.5  
  - wget 'http://sourceforge.net/projects/plantuml/files/plantuml.1.2018.2.jar/download' -O /tmp/plantuml.1.2018.2.jar  
  - gem install asciidoctor asciidoctor-diagram

script:
#  - sbt clean coverage test 
  - echo $JAVA_HOME
  - if [[ "$TRAVIS_SCALA_VERSION" == 2.12.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION  clean coverage test coverageReport && bash <(curl -s https://codecov.io/bash);
    else 
      sbt ++$TRAVIS_SCALA_VERSION  clean test makeSite && echo "Skipping code coverage reporting and docs on 2.13";
    fi  

jdk:
  - oraclejdk12
  - openjdk12

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: target/site
  on:
    branch: master
    condition: $TRAVIS_SCALA_VERSION = 2.13.2 AND $JAVA_HOME = /home/travis/openjdk12